name: Benim Depomdan İki Depoya Birden Güvenli Kopyala

on:
  push:
    branches:
      - main

jobs:
  sync-to-ramazan:
    runs-on: ubuntu-latest
    steps:
    - name: Kendi Depomu Klonla (emire0403)
      uses: actions/checkout@v4.2.2 # Güncel Node sürüm uyumlu hale getirildi

    - name: Git Kimlik Ayarlarını Yap
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    # --- 1. DEPO: SuperBlock Güncellemesi ---
    - name: SuperBlock Deposunu Güncelle
      run: |
        git clone https://${{ secrets.RAMAZAN_TOKEN }}@://github.com depo_1
        rsync -av --delete --exclude='.git/' --exclude='.github/' ./ depo_1/
        cd depo_1
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m "Otomatik Güncelleme: emire0403/superblock_web deposundan kopyalandı"
          git push origin main
        else
          echo "SuperBlock deponuz zaten güncel, değişiklik yok."
        fi
        cd ..
        rm -rf depo_1

    # --- 2. DEPO: superblock_web Güncellemesi ---
    - name: superblock_web Deposunu Güncelle
      run: |
        git clone https://${{ secrets.RAMAZAN_TOKEN }}@://github.com depo_2
        rsync -av --delete --exclude='.git/' --exclude='.github/' ./ depo_2/
        cd depo_2
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m "Otomatik Güncelleme: emire0403/superblock_web deposundan kopyalandı"
          git push origin main
        else
          echo "superblock_web deponuz zaten güncel, değişiklik yok."
        fi
        cd ..
        rm -rf depo_2
